In [1]:
import numpy as np

In [18]:
X = np.array([[0, 3, 1], [1, 3, 1], [0, 1, 1], [1, 1, 1]])
y = np.array([1, 1, 0, 0])
l = 0.07
w0 = np.array([-2, 1, 0])


In [20]:
s0 = 1 / (1 + np.exp(-X.dot(w0.T)))

In [21]:
s0

array([ 0.95257413,  0.73105858,  0.73105858,  0.26894142])

In [23]:
lambda_mat = l * np.identity(3)
omega_mat = (s0 * np.identity(4)) * ((1-s0) * np.identity(4))
lhs = lambda_mat + X.T.dot(omega_mat).dot(X)
rhs = (l * w0) - (X.T.dot(y - s0))

In [28]:
e1 = np.linalg.solve(a = lhs, b = rhs)
e1

array([-1.59414113, -0.81504991,  3.15199171])

In [30]:
w1 = w0 + e1
w1

array([-3.59414113,  0.18495009,  3.15199171])

In [31]:
s1 = 1 / (1 + np.exp(-X.dot(w1.T)))
s1

array([ 0.97603355,  0.52814543,  0.96567462,  0.4360523 ])

In [32]:
omega_mat = (s1 * np.identity(4)) * ((1-s0) * np.identity(4))
lhs = lambda_mat + X.T.dot(omega_mat).dot(X)
rhs = (l * w1) - (X.T.dot(y - s1))
e2 = np.linalg.solve(a = lhs, b = rhs)
e2

array([-2.57603702, -1.68435787,  5.06640044])

In [34]:
w2 = w1 + e2
w2

array([-6.17017815, -1.49940777,  8.21839216])